services:
  db:
    image: paradedb/paradedb:latest
    container_name: paradedb_compose
    restart: unless-stopped
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
      - POSTGRES_DB={DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - rag_data_18_v2:/var/lib/postgresql
      - ./architecture/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  rag_data_18_v2:


    